// Seeded by a one-time migration from the original main.go usage() block
// (#1095). There is no live generator yet (that is CLI-2's man/reference-gen
// work), so until then this map is maintained by hand alongside the command
// registry in runtime_capabilities.go: add a command there, add its synopsis
// line here. TestCLIVerbCoverage enforces that the two stay in sync.
package main

const gatherContextID = "gather-implement-context"

// synopsisByID holds each command's verbatim entry in the tiered usage lists,
// keyed by invocation-path id. The help renderers assemble these via the command
// registry so command discovery cannot drift from per-command help (#1095).
var synopsisByID = map[string]string{
	"temporal":               "  goobers temporal codec-server [flags] [path]  serve OIDC-authenticated payload decoding over TLS\n",
	"work-items":             "  goobers work-items [--provider=<name>] [--repository=<owner/name>] [--kind=<pr|issue>] [--id=<id>] [--limit=<n>] [--json] [--rebuild] [path]  list externally actioned pull requests and issues\n",
	"config-seed":            "  goobers config-seed --mirror <absolute-path> --instance <absolute-path>  seed a private worker instance from a rendered config mirror\n",
	"roots discover":         "  goobers roots discover [--json] [paths...]  find likely roots and report daemon ownership\n",
	"roots decommission":     "  goobers roots decommission --reason=<text> [path]  mark a stopped root as historical without deleting data\n",
	"queue-explain":          "  goobers queue-explain --gaggle=<name> --workflow=<name> --pr=<number> [--json] [path]  explain historical PR eligibility and claim evidence\n",
	"version":                "  goobers version [--json]      print build version, commit, and date (--json for structured output)\n",
	"versions":               "  goobers versions [--json]     print the supported DSL, Go toolchain, and OS/arch matrix\n",
	"init":                   "  goobers init [--allow-ephemeral] [--guided [--instance-path <dir>] [--port=<port|auto>] [--no-open] [--dev-assets=<dir>] [--workdir=<dir>] | --demo [--insecure] | --template=quickstart [--harness <name>] [--source-tree <path> [--json]] | --template=standard [--repo <repository>] [--branch <name>] [--issue-scope=all|assigned] [--assigned-to <identity>] [--pr-ci | --ci-command <JSON-argv> --required-capabilities <list>] [--workflows <list>] [--provider=github|ado] [--repo-auth-kind <kind>] [--repo-token-env <name>] [--work-tracking-token-env <name>] [--pr-token-env <name>] [--push-token-env <name>] [--github-cli-user <name>] [--model-token-env <name>] [--harness <name>]] [path]\n                                scaffold an instance, open guided setup with placement choices, or create a checked-in config source\n",
	"connect":                "  goobers connect <repository> [--token-env NAME] [--seed] [--replace] [--json] [path]\n                                connect an instance to a GitHub or Azure DevOps repository\n",
	"preflight":              "  goobers preflight [--instance <path> --workflow <name> [--execution-identity <actual>] [--check-readiness] [--json]] [--distro <name>] [--launch-wsl -- <command> [args...]]\n                                check WSL full-isolation readiness and optionally hand off a command\n",
	"onboarding":             "  goobers onboarding stub-agent-instructions [flags]\n                                run non-interactive onboarding actions\n",
	"examples":               "  goobers examples list | show <name>\n                                browse canonical workflow examples embedded in the binary\n",
	"scaffold":               "  goobers scaffold goober|workflow|gaggle [flags] <name> [path]\n                                scaffold a goober, workflow, or gaggle\n",
	"gaggle":                 "  goobers gaggle export|import [flags]\n                                export or import sanitized portable gaggle bundles\n",
	"diagnostics":            "  goobers diagnostics bundle|triage [flags] [path]\n                                collect redacted support evidence or classify one run before filing a defect\n",
	"harness":                "  goobers harness auth copilot status|login|logout [path]\n                                inspect or manage harness authentication without exposing credentials\n",
	"agent-kit":              "  goobers agent-kit install|check|update [flags] [path]\n                                install, inspect, or explicitly update the release-matched agent toolkit\n",
	"portal-extension":       "  goobers portal-extension install|status|update [flags]\n                                install, inspect, or update the user-scoped Goobers Portal canvas extension bundled with this binary\n",
	"validate":               "  goobers validate [--json] [--github-annotations] [--check-harness] [--check-repos] [--check-dispatch-namespaces] [--source-tree [--instance <path>]] [--strict] [path]\n                                validate an instance or checked-in config source tree\n",
	"lint":                   "  goobers lint [--json] [--github-annotations] [--check-harness] [--check-repos] [--check-dispatch-namespaces] [--source-tree [--instance <path>]] [--strict] [path]\n                                lint config via the single authoritative validation engine (alias for validate)\n",
	"fix":                    "  goobers fix (--to <version> | --instance-schema) [--write] [path]\n                                mechanically migrate workflows to a target dslVersion, or add the schemaVersion a runners: inventory requires\n",
	"doctor":                 "  goobers doctor (--k8s | --temporal-codec | --repo | --harness-auth | --av-exclusions) [--instance <root>] [--kubeconfig <path>] [--context <name>] [--report text|json] [--oidc-issuer <url>] [--registry <host>] [--egress <host:port,...>] [--temporal-hostport <host:port>] [--temporal-namespace <name>] [--timeout <duration>] [--work-root <dir>] [--overlay-dir <dir>] [--image-runtime docker|podman] [--image-pull-policy always|never] [--image-tools <tool,...>] [--image-ca <root.pem>] [--checks <id,...>] [--apiserver-endpoint <url>] [--record-instance <root>] [--result-max-age <duration>] [--psa-namespaces <namespace,...>] [--psa-service-account <name>]\n                                preflight Kubernetes, report Temporal codec or harness auth, compare forge policy, or verify antivirus exclusions\n",
	"netpol-render":          "  goobers netpol-render [--out <dir>] [--check] [--baseline <path>] [--write-baseline] [--timeout <duration>] [--print-blob-endpoint] [--keep-dns-for-network-none] [path]\n                                render per-runner-class NetworkPolicy reference manifests from the runners: inventory\n",
	"config":                 "  goobers config show|materialize|diff [flags] [path]\n                                inspect, materialize, or compare instance configuration\n",
	"speech":                 "  goobers speech preflight|test [flags] [path]\n                                preflight or test local speech notifications\n",
	"fleet":                  "  goobers fleet join|status|leave [flags] [path]\n                                associate this instance with a Fleet service (experimental; superseded)\n",
	"up":                     "  goobers up [--quiet] [--diagnostics] [--notify[=all]] [--watch-config] [--drain-timeout <duration>] [--skip-preflight] [--cleanup-spans-only-runs] [--disable-read-model-reads] [path]\n                                run the daemon (scheduler + runner + loopback HTTP API)\n",
	"down":                   "  goobers down [path]           request a live daemon's graceful drain-shutdown from a separate terminal\n",
	"apply":                  "  goobers apply [path]          reconcile a live daemon's workflow definitions from its configured source now\n",
	"self-update":            "  goobers self-update [--policy manual|on-release|on-main] [--include-prerelease] [--branch <name>] [--target <tag>] [--health-ticks <n>] [--health-timeout <duration>] [path]\n                                stage and request a supervised binary update\n",
	"service":                "  goobers service install|uninstall|stop|start|status|task-* [path]\n                                install and manage SCM or per-user Scheduled Task supervision\n",
	"service task-install":   "  goobers service task-install [path]\n                                install a per-user Windows Scheduled Task supervisor\n",
	"service task-uninstall": "  goobers service task-uninstall [path]\n                                remove the per-user Windows Scheduled Task supervisor\n",
	"service task-start":     "  goobers service task-start [path]\n                                start the per-user Windows Scheduled Task supervisor\n",
	"service task-stop":      "  goobers service task-stop [path]\n                                stop the per-user Windows Scheduled Task supervisor\n",
	"service task-status":    "  goobers service task-status [--json] [path]\n                                report per-user Windows Scheduled Task state and identity\n",
	"engine-start":           "  goobers engine-start [--gaggle <name>] [--temporal-hostport h:p] [--temporal-namespace <name>] [--task-queue <name>] [--direct] [--dedupe-key <key>] [--live-journal] <workflow> [path]\n                                dispatch one run onto the tier-3 engine (experimental)\n",
	"engine-queues":          "  goobers engine-queues [--temporal-hostport h:p] [--temporal-namespace <name>] [--task-queue <name>] [--timeout <duration>] [--json] [path]\n                                report which workers poll this instance's engine and dispatch task queues (experimental)\n",
	"engine-project":         "  goobers engine-project --gaggle <name> [--temporal-hostport h:p] [--temporal-namespace <name>] <run-id> [path]\n                                write a completed engine run's journal into the instance (experimental)\n",
	"worker":                 "  goobers worker [--task-queue <q>]... [--temporal-hostport h:p] [--temporal-namespace <name>] [--drain-timeout <dur>] [--work-root <path>] [--instance <path>] [--blob-store <path> | --blob-endpoint <url>] [--daemon-api <url>] [--dispatch-namespace <ns>] [--config-reload-interval <dur>] [--config-history-depth <n>]\n                                host a Temporal engine worker (tier-3, experimental)\n",
	"dashboard":              "  goobers dashboard [--port=<port|auto>] [--listen=<host:port>] [--wait-for-daemon[=<duration>]] [--no-open] [--dev-assets=<dir>] [path]\n                                serve and open the local operations portal\n",
	"run":                    "  goobers run [--force] [--gaggle <name>] [--github-progress] [--pr <number>] [--api <url> | --no-api] [--api-timeout <duration>] [--request-id <id>] [--expected-source-revision <digest>] <workflow> [--no-wait] [path]\n                                trigger a run manually; --force bypasses cadence budgets\n",
	"run abort":              "  goobers run abort [--api <url>] <run-id> [path]  mark a stuck non-terminal run aborted\n",
	"run cancel":             "  goobers run cancel [--api <url> | --no-api] [--request-id <id>] <run-id> [path]  cancel a live in-flight run via the daemon\n",
	"approve":                "  goobers approve [--decision=pass] [--actor=<identity>] [--api=<url>] <run-id> <gate> [path]  approve a paused or escalated gate\n",
	"override":               "  goobers override --rationale=<text> [--decision=pass] [--actor=<identity>] [--api=<url>] <run-id> <gate> [path]  override a nondeterministic gate\n",
	"rerun-stage":            "  goobers rerun-stage --addendum=<text> [--actor=<identity>] [--api=<url>] <run-id> <stage> [path]  rerun a stage with an instruction addendum\n",
	"signal":                 "  goobers signal <name> [path]  fire an external signal, dispatching every\n                                subscribed type=signal-trigger workflow\n",
	"workflow show":          "  goobers workflow show [--dot] <name> [path]  show a workflow as a text DAG\n",
	"runs list":              "  goobers runs list [--api=<url>] [--json] [--phase=...] [--workflow=...] [--gaggle=...] [--limit=N] [path]\n                                alias for the status run table (same flags, no --watch)\n",
	"runs du":                "  goobers runs du [--json] [path]       report per-run journal and artifact bytes\n",
	"status":                 "  goobers status [--api=<url>] [--daemon] [--agents] [--json] [--all] [--phase=...] [--workflow=...] [--gaggle=...] [--limit=N] [--watch [--interval=2s]] [path]\n                                validate config, show warnings, list runs newest first, report daemon health with --daemon, or list live agentic stages by role with --agents\n",
	"stats":                  "  goobers stats [--since <duration>] [--json] [path]\n                                show the instance lifetime summary card\n",
	"cost":                   "  goobers cost [--pr <id> | --issue <id>] [--provider <name>] [--window <duration> | --since <RFC3339>] [--until <RFC3339>] [--json] [--rebuild] [path]\n                                show bounded cost attribution by pull request or issue\n",
	"features":               "  goobers features [--json] [--dsl-version <version>] [--used] [path]\n                                list the workflow-DSL features this build supports\n",
	"schema":                 "  goobers schema <kind> | --list [--human]  emit a JSON Schema embedded in this build\n",
	"explain":                "  goobers explain [--human] <selector>      project field facts from an embedded JSON Schema\n",
	"reset-rate-limit":       "  goobers reset-rate-limit [path]  clear the hourly run-rate budget without deleting runs/\n",
	"workspace":              "  goobers workspace reset <repo> [path]  explicitly re-materialize a pinned workspace\n",
	"recovery-restore":       "  goobers recovery-restore [--record <record.json> | --issue <id> --repository-key <key>] --repository <checkout> --branch <new-branch> [instance]  restore retained implementation\n",
	"recovery-abandon":       "  goobers recovery-abandon --run <run-id> --ref <recovery-ref> --confirm-digest <patch-digest> [instance]  abandon one retained snapshot\n",
	"recovery-resume":        "  goobers recovery-resume [instance]  restore retained implementation into the receiving run\n",
	"blocked list":           "  goobers blocked list [--json] [path]   print the learned blocked-item ledger (scheduler/blocked.json)\n",
	"blocked clear":          "  goobers blocked clear <item-id> [path]  safely remove one blocked-item record, under claims.lock\n",
	"claims list":            "  goobers claims list [--json] [--stale] [--gaggle=name] [--provider=name] [path]\n                                print current claim leases, optionally only expired leases\n",
	"claims active":          "  goobers claims active [--json] [--gaggle=name] [--provider=name] [path]\n                                print what is actively claimed now: item, workflow, run, holder, and age\n",
	"claims release":         "  goobers claims release [--force] [--gaggle=name --provider=name] <item-id> [path]\n                                force-release a claim through the live daemon or claims.lock\n",
	"cancel-pending-ci":      "  goobers cancel-pending-ci [path]  cancel bounded pending CI for an exact reviewed PR head\n",
	"trace":                  "  goobers trace [--api=<url>] [--json] [--follow] [--after-seq=<seq>] [--summary | --verdicts] [--transcripts | --transcript=<stage>] <run-id> [path]\n                                show a run's journal events, review verdicts, follow a live run, or show recorded agent transcripts\n",
	"e2e verify":             "  goobers e2e verify --run <run-id> [--gaggle <name>] [--expected <topology.json>] [--out <bundle.json>] [--print-runner-class <restrictions>] [path]\n                                verify the Goobernetes S1-S9 e2e proof harness's assertions against one completed run's recorded data\n",
	"e2e kill-inject":        "  goobers e2e kill-inject --run <run-id> --stage <name> --stage-class <builtin|agentic|local-ci> --namespace <ns> [--poll-timeout <duration>] [--out <record.json>]\n                                perform one live S6 kill-matrix cell (pod-kill) against a real cluster\n",
	"escalations":            "  goobers escalations [--api=<url>] [--json] [--limit=<n>] [--since=<time>] [path]\n                                list escalated runs newest first\n",
	"escalations show":       "  goobers escalations show [--api=<url>] [--json] [--include-verdict] <run-id> [path]\n                                show escalation cause, verdict, and per-stage artifact timeline\n",
	"escalations resolve":    "  goobers escalations resolve --resolution=approve|deny|redirect [--gate=<gate>] [--decision=<name>] [--rationale=<text>] [--actor=<identity>] [--api=<url>] <run-id> [path]\n                                resolve an escalated run through the daemon's HITL plane\n",
	"completion":             "  goobers completion bash|zsh|fish|powershell  generate a shell completion script\n",
	"telemetry":              "  goobers telemetry configure|test|stats|merges|errors|export|mark-fix|prune|prune-orphans|compact [flags] [path]\n                                configure, test, query, export, mark fixes, prune, or compact telemetry\n",
	"journal redact":         "  goobers journal redact --run <id> --path <blob> --reason <text> [--secret-file <f>] [path]\n                                remove a leaked secret from a stored blob (SEC-041)\n",
	"backlog-dedupe":         "  goobers backlog-dedupe                 surface ranked duplicate candidates for curator judgment (a workflow stage)\n",
	"backlog-assignment":     "  goobers backlog-assignment             assign eligible backlog items from a configured roster (a workflow stage)\n",
	"backlog-health":         "  goobers backlog-health [--feedback]    snapshot ready-pool depth and age (a workflow stage)\n",
	"backlog-query":          "  goobers backlog-query [--debug] [--read-only | --claim [--resweep] | --reconcile | --release]  query/claim one eligible backlog item (a workflow stage)\n",
	"select-source":          "  goobers select-source                  select and claim an unconsumed L6 decomposition disposition (a workflow stage)\n",
	"validate-plan":          "  goobers validate-plan                  validate a decomposition plan against its selector artifact and the live parent (a workflow stage)\n",
	"publish-batch":          "  goobers publish-batch                  publish a verified decomposition batch behind one eligibility barrier (a workflow stage)\n",
	"file-issues":            "  goobers file-issues [--check]          file a validated nominations artifact as deduped, budgeted issues (a workflow stage)\n",
	"reconcile-branches":     "  goobers reconcile-branches [--delete] [--max N] [--min-age D] [--after BRANCH]\n                                report bounded stale goobers/* branch candidates; --delete opts into removal (a workflow stage)\n",
	"push-branch":            "  goobers push-branch [--config-repo]    push the worktree's checked-out branch to origin (a workflow stage)\n",
	"preflight-repo-write":   "  goobers preflight-repo-write            check whether the configured credential can push this run's branch namespace, without mutating anything (a workflow stage)\n",
	"config-checkout":        "  goobers config-checkout                 clone the instance config repository for a config-repo-targeted stage (a workflow stage)\n",
	"check-fail-first":       "  goobers check-fail-first                enforce fail-first evidence for a new workflow gate (a workflow stage)\n",
	"open-pr":                "  goobers open-pr [--config-repo]        open or update the run's PR (a workflow stage)\n",
	"report-pr-status":       "  goobers report-pr-status               publish goobers' verdict + CI evidence as a policy-gate-able PR status (a workflow stage)\n",
	"gate-removal-guard":     "  goobers gate-removal-guard [--config-repo] block a tutor run that removes/loosens its own flagged gate without proof (a workflow stage)\n",
	"issue-close-out":        "  goobers issue-close-out                comment + close out the claimed issue (a workflow stage)\n",
	"pr-comment-watch":       "  goobers pr-comment-watch               label open goober PRs with unaddressed human comments goobers:needs-remediation (a workflow stage)\n",
	"set-milestone":          "  goobers set-milestone --item ID --milestone N [path]\n                                assign an existing milestone to an issue (a workflow stage)\n",
	"merge-pr":               "  goobers merge-pr                       conjunctive auto-merge \u2014 verdict=pass + CI green + not-draft + SHA-pin valid; lands via direct-merge or merge-queue-enqueue per the repo's detected merge policy (a workflow stage)\n",
	"merge-queue-poll":       "  goobers merge-queue-poll               watch an enqueued pull request until merged, evicted, timed out, or opted out; dequeue opt-outs and route failures (a workflow stage)\n",
	"reconcile-post-merge":   "  goobers reconcile-post-merge [--max N] [--lookback D]\n                                reconcile bounded late merge-queue merges through post-merge bookkeeping (a workflow stage)\n",
	"record-merge-refusal":   "  goobers record-merge-refusal           record a merge refusal and demote a persistently-stuck lander (a workflow stage)\n",
	"post-merge":             "  goobers post-merge                     post-merge fan-out (label behind PRs) + close the referenced issue (a workflow stage)\n",
	"security-alerts-query":  "  goobers security-alerts-query --source code-scanning|dependabot [--state <state>] [--severity <list>] [--tool <name>] [--ref <ref>] [--ecosystem <list>] [--scope runtime|development] [--max-results <n>]\n                                emit bounded, untrusted security alerts for work nomination (a connector stage)\n",
	"telemetry-query":        "  goobers telemetry-query [--window <d>] [--aggregate <name>] [--learning-action <name>] [--threshold <k=v>] [--format candidate-findings] [--gaggle <name>] [--workflow <name>]\n                                emit versioned candidate findings (a connector stage)\n",
	"docs-churn":             "  goobers docs-churn [--repo <dir>] [--workflow <name>] [--gaggle <name>] [--since <d>] [--buffer-multiplier <f>] [--format churn-digest]\n                                emit the docs-drift churn digest since the watermark (a connector stage)\n",
	"ios-simulator-test":     "  goobers ios-simulator-test (--project <path> | --workspace <path>) --scheme <name> [--device <name>] [--runtime <id>] [--only-testing <test>] [--result-bundle <path>]\n                                run XCUITest on an iOS simulator and parse its xcresult (a workflow stage)\n",
	"pr-select":              "  goobers pr-select                      select one managed or advisory open PR for merge-review (a workflow stage)\n",
	"check-issue-staleness":  "  goobers check-issue-staleness          route a PR to remediation if its linked issue changed since implementation began (a workflow stage)\n",
	"gather-sibling-context": "  goobers gather-sibling-context [--no-cache] [--no-verdict-cache]  load other open PRs' files/state as review evidence (a workflow stage)\n",
	gatherContextID:          "  goobers gather-implement-context       load first-pass verdict taxonomy and hot-file context (a workflow stage)\n",
	"apply-verdict":          "  goobers apply-verdict [--gate <name>]  publish a managed or advisory merge-review verdict (a workflow stage)\n",
	"elect-lander":           "  goobers elect-lander [--gate <name>]   elect the landing PR among a merge-review cohort (a workflow stage)\n",
	"update-behind-pr":       "  goobers update-behind-pr               API-update a clean behind-base PR, otherwise route to full remediation (a workflow stage)\n",
	"pr-claim":               "  goobers pr-claim [--release]           check PR liveness or release its remediation claim (a workflow stage)\n",
	"gather-pr-context":      "  goobers gather-pr-context              pr-remediation entrypoint: select a needs-remediation PR, check out its branch, load verdict/thread/behind-base context (a workflow stage)\n",
	"gather-review-threads":  "  goobers gather-review-threads          add native reviews and anchored inline threads to a remediation brief (a workflow stage)\n",
	"resolve-review-threads": "  goobers resolve-review-threads         reply to and resolve remediated native review threads (a workflow stage)\n",
	"gather-issue-context":   "  goobers gather-issue-context           add originating issue bodies to a remediation brief (a workflow stage)\n",
	"gather-ci-failures":     "  goobers gather-ci-failures             add failing check summaries and annotations to a remediation brief (a workflow stage)\n",
	"rebase-pr":              "  goobers rebase-pr                      rebase-first, finding-driven routing: clean+no-substantive force-pushes and clears the label, else defers to agentic remediation (a workflow stage)\n",
	"remediation-checkpoint": "  goobers remediation-checkpoint [--budget N] [--escalate <reason> [--escalation-outcome <outcome>]]  durable per-cause attempt budgets + same-diff escalation (a workflow stage)\n",
	"push-remediated":        "  goobers push-remediated                force-push the remediated branch to the claimed PR and clear needs-remediation (a workflow stage)\n",
	"respond-to-findings":    "  goobers respond-to-findings [--check]  post a validated per-finding remediation response to the claimed PR (a workflow stage)\n",
	"mcp-io":                 "  goobers mcp-io --config <path>         run the generic goobers-io MCP server over stdio (harness-spawned, not run by hand)\n",
}
