// Code generated by go generate ./internal/apicontract; DO NOT EDIT.

export const apiRoutes = {
  "discovery": { method: "GET", path: "/.well-known/goobers", actionClass: "api-metadata" },
  "openapi": { method: "GET", path: "/api/v1/openapi.json", actionClass: "api-metadata" },
  "capabilities": { method: "GET", path: "/api/v1/capabilities", actionClass: "api-metadata" },
  "health": { method: "GET", path: "/api/v1/health", actionClass: "read-only-navigation" },
  "readiness": { method: "GET", path: "/api/v1/instance/readiness", actionClass: "read-only-navigation" },
  "configDigest": { method: "GET", path: "/api/v1/config/digest", actionClass: "read-only-navigation" },
  "workerConfigDivergence": { method: "POST", path: "/api/v1/worker/config-divergence", actionClass: "workflow-execution" },
  "instance": { method: "GET", path: "/api/v1/instance", actionClass: "read-only-navigation" },
  "portalConfig": { method: "GET", path: "/api/v1/portal/config", actionClass: "read-only-navigation" },
  "portalAsset": { method: "GET", path: "/assets/{path...}", actionClass: "read-only-navigation" },
  "gaggles": { method: "GET", path: "/api/v1/gaggles", actionClass: "read-only-navigation" },
  "gaggleGoobers": { method: "GET", path: "/api/v1/gaggles/{gaggle}/goobers", actionClass: "read-only-navigation" },
  "gaggleWorkflows": { method: "GET", path: "/api/v1/gaggles/{gaggle}/workflows", actionClass: "read-only-navigation" },
  "gaggleConnections": { method: "GET", path: "/api/v1/gaggles/{gaggle}/connections", actionClass: "read-only-navigation" },
  "gaggleBundleExport": { method: "GET", path: "/api/v1/gaggles/{gaggle}/bundle", actionClass: "read-only-navigation" },
  "gaggleBundleImport": { method: "POST", path: "/api/v1/gaggles/import", actionClass: "maintenance" },
  "workflowDetail": { method: "GET", path: "/api/v1/gaggles/{gaggle}/workflows/{workflow}", actionClass: "read-only-navigation" },
  "workflowQueueEligibility": { method: "GET", path: "/api/v1/gaggles/{gaggle}/workflows/{workflow}/queue-eligibility", actionClass: "read-only-navigation" },
  "runs": { method: "GET", path: "/api/v1/runs", actionClass: "read-only-navigation" },
  "runDetail": { method: "GET", path: "/api/v1/runs/{run}", actionClass: "read-only-navigation" },
  "runReveal": { method: "POST", path: "/api/v1/runs/{run}/reveal", actionClass: "maintenance" },
  "runEvents": { method: "GET", path: "/api/v1/runs/{run}/events", actionClass: "read-only-navigation" },
  "stageAttempts": { method: "GET", path: "/api/v1/runs/{run}/stages/{stage}/attempts", actionClass: "read-only-navigation" },
  "runArtifact": { method: "GET", path: "/api/v1/runs/{run}/artifacts/{digest}", actionClass: "read-only-navigation" },
  "runRecovery": { method: "GET", path: "/api/v1/runs/{run}/recovery", actionClass: "read-only-navigation" },
  "runRecoveryPublish": { method: "POST", path: "/api/v1/runs/{run}/recovery", actionClass: "workflow-execution" },
  "runTranscript": { method: "GET", path: "/api/v1/runs/{run}/transcripts/{seq}", actionClass: "read-only-navigation" },
  "telemetryCosts": { method: "GET", path: "/api/v1/telemetry/costs", actionClass: "read-only-navigation" },
  "telemetryStats": { method: "GET", path: "/api/v1/telemetry/stats", actionClass: "read-only-navigation" },
  "telemetryErrorSignatures": { method: "GET", path: "/api/v1/telemetry/error-signatures", actionClass: "read-only-navigation" },
  "telemetryErrors": { method: "GET", path: "/api/v1/telemetry/errors", actionClass: "read-only-navigation" },
  "workItems": { method: "GET", path: "/api/v1/work-items", actionClass: "read-only-navigation" },
  "workItemDetail": { method: "GET", path: "/api/v1/work-items/{provider}/{kind}/{id}", actionClass: "read-only-navigation" },
  "telemetryImplementationOutcomes": { method: "GET", path: "/api/v1/telemetry/implementation-outcomes", actionClass: "read-only-navigation" },
  "telemetryDefectAggregates": { method: "GET", path: "/api/v1/telemetry/defect-aggregates", actionClass: "read-only-navigation" },
  "events": { method: "GET", path: "/api/v1/events", actionClass: "read-only-navigation" },
  "approveStage": { method: "POST", path: "/api/v1/runs/{run}/stages/{stage}/approve", actionClass: "runtime-mutation", capability: "approve" },
  "overrideStage": { method: "POST", path: "/api/v1/runs/{run}/stages/{stage}/override", actionClass: "runtime-mutation", capability: "override" },
  "rerunStage": { method: "POST", path: "/api/v1/runs/{run}/stages/{stage}/rerun", actionClass: "runtime-mutation", capability: "rerun" },
  "workflowEnabled": { method: "PUT", path: "/api/v1/gaggles/{gaggle}/workflows/{workflow}/enabled", actionClass: "maintenance" },
  "claimAcquire": { method: "POST", path: "/api/v1/claims/acquire", actionClass: "workflow-execution" },
  "claimRenew": { method: "POST", path: "/api/v1/claims/renew", actionClass: "workflow-execution" },
  "claimRelease": { method: "POST", path: "/api/v1/claims/release", actionClass: "workflow-execution" },
  "claimSettle": { method: "POST", path: "/api/v1/claims/settle", actionClass: "workflow-execution" },
  "claimList": { method: "POST", path: "/api/v1/claims/list", actionClass: "workflow-execution" },
  "claimVerify": { method: "POST", path: "/api/v1/claims/verify", actionClass: "workflow-execution" },
  "claimRecover": { method: "POST", path: "/api/v1/claims/recover", actionClass: "workflow-execution" },
  "claimsActive": { method: "GET", path: "/api/v1/claims/active", actionClass: "read-only-navigation" },
  "triggerIngest": { method: "POST", path: "/api/v1/triggers", actionClass: "workflow-execution" },
  "triggerStatus": { method: "GET", path: "/api/v1/triggers/{acceptance}", actionClass: "read-only-navigation" },
  "workflowStart": { method: "POST", path: "/api/v1/workflows/start", actionClass: "workflow-execution" },
  "resolveEscalation": { method: "POST", path: "/api/v1/runs/{run}/escalation/resolve", actionClass: "maintenance" },
  "cancelRun": { method: "POST", path: "/api/v1/runs/{run}/cancel", actionClass: "maintenance" },
  "journalEmit": { method: "POST", path: "/api/v1/runs/{run}/journal/emit", actionClass: "workflow-execution" },
  "credentialResolve": { method: "POST", path: "/api/v1/credentials/resolve", actionClass: "workflow-execution" },
  "credentialRefresh": { method: "POST", path: "/api/v1/credentials/refresh", actionClass: "workflow-execution" },
  "stageSurrender": { method: "POST", path: "/api/v1/runs/{run}/stages/{stage}/attempts/{attempt}/surrender", actionClass: "workflow-execution" },
  "stageSurrenderGet": { method: "GET", path: "/api/v1/runs/{run}/stages/{stage}/attempts/{attempt}/surrender", actionClass: "read-only-navigation" },
  "stageSurrenderSeen": { method: "GET", path: "/api/v1/runs/{run}/stages/{stage}/attempts/{attempt}/surrender/seen", actionClass: "read-only-navigation" },
  "blobGet": { method: "GET", path: "/api/v1/blobs/{digest}", actionClass: "read-only-navigation" },
  "blobPut": { method: "PUT", path: "/api/v1/blobs/{digest}", actionClass: "workflow-execution" },
  "gaggleStateGet": { method: "GET", path: "/api/v1/gaggles/{gaggle}/state/{key}", actionClass: "read-only-navigation" },
  "gaggleStatePut": { method: "PUT", path: "/api/v1/gaggles/{gaggle}/state/{key}", actionClass: "workflow-execution" },
  "journalRunPhase": { method: "POST", path: "/api/v1/journal/run-phase", actionClass: "workflow-execution" },
  "journalConflictTouches": { method: "POST", path: "/api/v1/journal/conflict-touches", actionClass: "workflow-execution" },
  "journalUnpushedWork": { method: "POST", path: "/api/v1/journal/unpushed-work", actionClass: "workflow-execution" },
  "journalEscalationCandidates": { method: "POST", path: "/api/v1/journal/escalation-candidates", actionClass: "workflow-execution" },
  "journalMergeAuthority": { method: "POST", path: "/api/v1/journal/merge-authority", actionClass: "workflow-execution" },
  "journalBranchOwnership": { method: "POST", path: "/api/v1/journal/branch-ownership", actionClass: "workflow-execution" },
  "operatorMessageSubmit": { method: "POST", path: "/api/v1/runs/{run}/operator-messages", actionClass: "workflow-execution" },
} as const;

export type ApiRoute = (typeof apiRoutes)[keyof typeof apiRoutes];

export const configAuthoringRoutes = {
  "configSources": { method: "GET", path: "/api/v1/config/sources", actionClass: "read-only-navigation" },
  "configSourceDocuments": { method: "GET", path: "/api/v1/config/sources/{source}/documents", actionClass: "read-only-navigation" },
  "configSourceDocument": { method: "GET", path: "/api/v1/config/sources/{source}/document", actionClass: "read-only-navigation" },
  "configSourcePreview": { method: "POST", path: "/api/v1/config/sources/{source}/preview", actionClass: "config-time" },
  "configSourceChanges": { method: "PUT", path: "/api/v1/config/sources/{source}/changes", actionClass: "config-time" },
} as const;

export type ConfigAuthoringRoute =
  (typeof configAuthoringRoutes)[keyof typeof configAuthoringRoutes];

export const configAuthoringErrorCodes = ["config_source_not_found", "config_document_not_found", "config_stale_revision", "config_unsupported_capability", "config_validation_failed", "config_authorization_failed", "config_projection_lag"] as const;

export type ConfigAuthoringErrorCode =
  (typeof configAuthoringErrorCodes)[number];

export const runtimeMutationCapabilities = ["approve", "override", "rerun"] as const;

export type RuntimeMutationCapabilityId =
  (typeof runtimeMutationCapabilities)[number];

export const actionClasses = {
  runtimeMutation: "runtime-mutation",
  readOnlyNavigation: "read-only-navigation",
  apiMetadata: "api-metadata",
  configTime: "config-time",
  daemonLifecycle: "daemon-lifecycle",
  workflowExecution: "workflow-execution",
  maintenance: "maintenance",
} as const;

export type ActionClass =
  (typeof actionClasses)[keyof typeof actionClasses];

export type SurfaceAction =
  | { id: string; class: typeof actionClasses.runtimeMutation; capability: RuntimeMutationCapabilityId }
  | { id: string; class: Exclude<ActionClass, typeof actionClasses.runtimeMutation>; capability?: never };
